version: '3'
services:
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data  # Utilisation d'un volume pour les données Redis

  web:
    build: .
    container_name: web-container
    ports:
      - "5000:8080"
    environment:
      - REDIS_HOST=redis-container
    volumes:
      - app_data:/app  # Utilisation d'un volume pour les données de l'application web

# ajout d'autres services ou configurations ici si nécessaire

volumes:
  redis_data:  # Définition du volume pour Redis
  app_data:    # Définition du volume pour l'application web
