# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_ANSIBLE_VERSION'] = '1.8'

Vagrant.configure("2") do |config|

  # Define the gitlab_server VM
  config.vm.define "userapi_server" do |server|

      # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "centos/7"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network :forwarded_port, guest: 80, host: 8080, auto_correct: true
  config.vm.network :forwarded_port, guest: 9000, host: 9000, auto_correct: true
  config.vm.network :forwarded_port, guest: 5000, host: 5000, auto_correct: true
  # Enable provisiong with bash script
  #config.vm.provision "shell", path: "bootstrap.sh"

  config.ssh.forward_x11 = true

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  #config.vm.synced_folder "./src", "/home/vagrant/src"

 config.vm.provider "virtualbox" do |v|
      v.name = "userapi.server.local"
      v.gui = true  # Boot with GUI (optional)
      v.customize ["modifyvm", :id, "--memory", "2048", "--cpus", "2"]
    end

  end
  # Share the application source code folder with the VM
  config.vm.synced_folder "../userapi/src", "/home/vagrant/src"

# Use Vagrant Ansible provisioner
config.vm.provision "ansible_local" do |ansible|
  # The path to the playbooks entry point
  ansible.playbook = "playbooks/run.yml"
  # Only run the roles with these tags
  ansible.tags = "install"
  end

end
