apiVersion: v1
kind: Service
metadata:
  name: monapp-service
spec:
  type: NodePort
  selector:
    app: monapp 
  ports:
    - port: 30365  # Port à l'extérieur du cluster
      targetPort: 3000  # Port à l'intérieur du conteneur