version: '3'

services:
  node-app:
    build:
      context: ./userapi
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    depends_on:
      - redis
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
