name: node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 2s
          --health-retries 3

    steps:
    - name: Modify hosts file
      run: echo "127.0.0.1 redis" | sudo tee -a /etc/hosts

    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'
        node-version-file: 'userapi/package-lock.json'
    
    - name: Install dependencies
      run: |
        cd userapi
        npm install
        npm ci
        npm run build --if-present
    
    - name: Run tests
      run: |
        cd userapi
        npm test -- --exit
