apiVersion: v1
kind: Service
metadata:
  name: kubernetes-bootcamp-service
spec:
  type: NodePort
  selector:
    app: kubernetes-bootcamp  
  ports:
    - port: 30365     # port sur lequel on execute le conteneur ici 30365
      targetPort: 8080 # port sur lequel l'application web node.js
